[package]
name = "xgamerman626/ecsgame"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
matter = "evaera/matter@0.6.2"
plasma = "evaera/plasma@0.4.2"